---
title: "Data & Apps"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

On this page you will find links to datasets used in research as well as some more interactive stuff. The Apps allow for more direct interaction with the data and in some cases contain downloading options. 
<br/><br/>

# Apps
Here you can view some of my Apps. In some cases datasets can be directly downloaded -alternatively navigate to the data sections of this webpage.
<br/><br/>

### Direct Democracy apps
  
#####<a href="https://fmendez72.github.io/web/pages/eu2017.html" target="_blank">Referendums on European integration</a> 
[This App draws my co-authored CUP book (2014) and report for the European Parliament (2017)]
<br/><br/>

#####<a href="https://fmendez72.github.io/web/pages/sovereignty.html" target="_blank">Sovereignty referendums (1776-2014)</a> 
[This App draws on my (2018) paper with Micha Germann on Contested Sovereignty]
<br/><br/>

##### [Referendum provisions and practice in Europe]()
[This App draws on work for the LIDD team; this is a work in progress, App to be released soon.]
<br/><br/>

### Public Opinion apps

#####<a href="https://fmendez72.github.io/web/pages/refDemand.html" target="_blank">Demand for referendums across the European Union</a> 
[This App uses a number of public opinion datasets that asked questions about the desirability of referendums. I originally developed the App for a project with the EUI's Robert Schuman Centre for Advanced Studies in Florence.]
<br/><br/>

#### [Election 1](https://fmendez72.github.io/FM_webtest/Liddpages/ConceptualMap.html)
<br/><br/>

# Data
Below you can find links to mainly publicly archived datasets connected to research projects.

<br/>

### Public Opinion data

#####<a href="https://data.gesis.org/sharing/#!Detail/10.7802/1750" target="_blank">EUvox 2014: European Parliament elections</a> 
[EUvox2014 was a Voting Advice Application (VAA) deloyed for the European Parliament elections of 2014. The user data contains over a million entries from 22 countries]
<br/><br/>

#### [Election Y](https://fmendez72.github.io/FM_webtest/Liddpages/ConceptualMap.html)

<br/>

### Party positions

#####<a href="https://data.gesis.org/sharing/#!Detail/10.7802/1594" target="_blank">Party positions European elections 2014</a> 
[This dataset contains the positions of 231 political parties, across 28 countries, on 30 policy issues that were considered salient for the 2014 elections to the European Parliament. The party position estimates were originally used in a voter information tool which compared the policy preferences of citizens to those of political parties]
<br/><br/>

### Direct Democracy

#### [Referendums on European integration ](https://fmendez72.github.io/FM_webtest/Liddpages/ConceptualMap.html)
<br/>

#####<a href="https://data.gesis.org/sharing/#!Detail/10.7802/1594" target="_blank">Sovereignty referendums: 1776:2014</a> 
[The *Contested Sovereignty* data set documents the worldwide use of the sovereignty referendum, since 1776. It contains data on over 600 sovereignty referendums.]

<br/>

