---
title: "Research"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 2
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

<br/>
This page lists some of my main research areas. It includes both recent and ongoing research. Use the table of contents box to navigate directly to the different research areas. For a more comprehensive list of publications see the [Bio/Publications](https://fmendez72.github.io/web/bio.html) tab.
<br/><br/>

## Direct Democracy
Much of my research has focused on direct democraqcy and other forms of political participation. A lot of this work was done while I was at the [c2d](http://c2d.ch), the leading centre for the study of direct democracy. Below is a sample of recent work and ongoing research: <br/>

[(in press) The Law and Politics of Direct Democracy in the European Union in P.J. Cardwell and M-P. Granger (eds), *Research Handbook on the Politics of EU Law*. Edward Elgar (with M. Mendez)]( https://www.e-elgar.com/shop/gbp/research-handbook-on-the-politics-of-eu-law-9781788971270.html)

(in press) EU Accession Referendums in J. Smith (ed) *The Palgrave Handbook on European Referendums* (with M. Mendez)

[(2018) Contested Sovereignty: Mapping Referendums on Sovereignty over Time and Space. *British Journal of Political Science* (with M. Germann)]( https://doi.org/10.1017/S0007123415000563)

[(2018) Referendums on European Integration: Crisis Solving or Crisis Inducing?, in (eds) Morel, L. & Qvortrup, M. *Routledge Compendium on Direct Democracy* (with M. Mendez)]( https://www.routledgehandbooks.com/doi/10.4324/9780203713181-23)

[(2017) Referendums on EU Matters: *Study commissioned by the European Parliament* (with M. Mendez)]( https://www.europarl.europa.eu/RegData/etudes/STUD/2017/571402/IPOL_STU%282017%29571402_EN.pdf)

[(2017) The promise and perils of direct democracy for the European Union. *Cambridge Yearbook of European Legal Studies* (with M. Mendez)]( https://doi.org/10.1017/cel.2017.7)

[(2016) The European Union and direct democracy: An overview. In Ruth, S., Y. Welp & L. Whitehead. (Eds) Let the people rule? Direct democracy in the twenty-first century, *ECPR Press* (with M. Memdez).]( https://www.researchgate.net/publication/318263485_Let_the_People_Rule_Direct_Democracy_in_the_Twenty-First_Century)

[(2014) Referendums and the European Union: A comparative inquiry. *Cambridge University Press* (with Mendez, M., Triga, V.) ]( https://doi.org/10.1017/CBO9781139524117)
<br/>

##### Ongoing research
I am involved in an interdisciplinary European Research Council project, [LIDD](https://www.ivr.uzh.ch/en/institutsmitglieder/moeckli/Research-project-LIDD.html), which focuses on the limits of direct democracy. Within the project I am currently exploring two main areas

1. *Mapping institutions of direct democracy across the 48 member states of the Council of Europe*. This project is presently focused on developing a new database of institutions and practices in the CoE states [[see more]](https://www.ivr.uzh.ch/en/institutsmitglieder/moeckli/Research-project-LIDD.html).

2. *The Agenda inititive in Europe and America: A cross-regional perspective* This project focuses on large country comparison of one of the least well understood instruments of direct democracy that is nonethless surprisingly popular in Europe and America.

<br/>

## Political behaviour
This research area includes various themes related to the study of political attitudes, party politics and especially voting behaviour. A lot of the research draws on data generated from voting advice applications.

[(2019) Reconceptualising Dimensions of Political Competition in Europe. *British Journal of Political Science* (with J. Wheatley)](https://doi.org/10.1017/S0007123418000571)

[(2018) Does receiving advice from Voter Advice Applications (VAAs) affect public opinion in deeply divided societies? Evidence from a field experiment in Northern Ireland. *Party Politics* (with Garry, J., Tilly, J., Matthews, N., & J Wheatley)](https://doi.org/10.1177/1354068818818789)

[(2018) Helping citizens to locate political parties in the policy space: A dataset for the 2014 elections to the European Parliament. *Research Data Journal for the Humanities and Social Sciences* (with Gemenis, K., and J Wheatley)](https://doi.org/10.1163/24523666-00401002)

[(2017) Modeling proximity and directional decisional logic: What can we learn from applying statistical learning techniques to VAA-generated data? *Journal of Elections, Public Opinion and Parties*](https://doi.org/10.1080/17457289.2016.1269113)

[(2016) Dynamic scale validation reloaded: Assessing the psychometric properties of latent measures of ideology in VAA spatial maps. *Quality & Quantity* (with M. Germann)](https://doi.org/10.1007/s11135-015-0186-0)

[(2015) Spatial maps in voting advice applications: The case for dynamic scale validation. *Acta Politica* (with Germann, M., Wheatley, J., & Serdült, U)](https://doi.org/10.1057/ap.2014.3)

[(2014) The dimensionality of the Scottish political space: Results from an experiment on the 2011 Holyrood elections. *Party Politics* (with Wheatley, J., Carman, C., & Mitchell, J.)](https://doi.org/10.1177/1354068812458614)

[(2014) Mapping political parties in the ideological space with VAA data. in: Garzia, D., Marschall, S. (Eds.), *Matching Voters with Parties and Candidates*, ECPR Press (with J. Wheatley)](https://www.researchgate.net/publication/285054037_Matching_Voters_With_Parties_and_Candidates_Voting_Advice_Applications_in_a_Comparative_Perspective/link/588b7fb0a6fdcc8e63c802d2/download)


##### Ongoing research
I have two ongoing research collaborations with Kostas Gemenis and Micha Germann in the area of political behaviour.

1. A project that focuses on re-evaluating spatial voting models in a Big Data context.
2. A paper that focuses on the role of political information provision and party support.

<br/>

## Political communication
I have a strong interest in applied political communication research. Much of this work is focused on the design and impact of voting advice applications as well as developing coding and annotation platforms. Recently, I have started to use computational text analysis techniques (such as topic modeling and sentiment analysis) to evaluate, for instance news coverage during elections and the communication of EU public policies.

[(2020) EU Cohesion Policy under the Media Spotlight: Exploring Territorial and Temporal Patterns in News Coverage and Tone. *Journal of Common Market Studies* (with Mendez, C., Trigka V., & J Carrascosa)]()

[(2019) The Visibility and Communication of Cohesion Policy in Online Media. *Study commissioned by the European Parliament's REGI Committee*](https://www.europarl.europa.eu/RegData/etudes/STUD/2019/629196/IPOL_STU(2019)629196_EN.pdf)

[(2018) Post-crisis political normalisation? The Cyprus 2018 Presidential elections in context. *South European Society and Politics* (Triga, V. & C Djouvas)](https://doi.org/10.1080/13608746.2018.1511347)


[(2014) What’s behind a matching algorithm: A critical assessment of how VAAs produce voting recommendations, in: Garzia, D., Marschall, S. (Eds.), *Matching Voters with Parties and Candidates*, ECPR Press](https://www.researchgate.net/publication/285054037_Matching_Voters_With_Parties_and_Candidates_Voting_Advice_Applications_in_a_Comparative_Perspective/link/588b7fb0a6fdcc8e63c802d2/download)

[(2012) Matching voters with political parties and candidates: An empirical test of four algorithms. *International Journal of Electronic Governance*](https://fmendez72.github.io/web/pages/ijeg.pdf)

##### Ongoing research
I am working with a team from Cyprus University of Technology in two new areas:

1. Exploiting Big Data (mostly from Twitter) to explore vote preferences during referendum campaigns.
2. Developing algorithms to analyse discussions on Twitter related to EU policies.

<br/>

## Digital politics & policy
This is a broad area of research that focuses on digital politics, such as electronic participation, and public policy concerns mostly related to internet governance. 

[(2017) What drives fidelity to internet voting? Evidence from the roll-out of internet voting in Switzerland. *Government and Information Quarterly* (with U Serdült)]()

[(2015). Who are the internet voters? In E. Tambouris et al. (Eds.) Electronic Government and Electronic Participation. (with Serdult, U., Germann, M., Harris, M. & A Portenier)]()

[(2014) From initial idea to piecemeal implementation Switzerland’s first decade of Internet voting reviewed. In Zissis, D., and Lekkas, D. (Eds) *Design, Development, and Use of Secure Electronic Voting Systems* IGI Global (with U Serdült)]()

[(2015) Fifteen years of internet voting in Switzerland (history, governance and use). In Teran, L and A Meier, eDemocracy & eGovernment (ICEDEG), 2015 Second International Conference IEEE Xplore (with Serdult, U., Germann, M., Portenier, A., &C Wellig)]()

[(2013) EU-Democracy & E-Democracy: Can the two be reconciled? In K Demetriou (ed) *Democracy in Transition: Political Participation in the European Union* Springer]()

[(2012) Political polarization and popularity in online participatory media: an integrated approach. Proceedings of the 21st ACM International Conference on Information Knowledge Management (with Garcia, D., Serdült, U., & F Schweitzer)]()

[(2010) Comparing privacy regimes: Federal theory and the politics of privacy regulation in the European Union and the United States. *Publius: Journal of Federalism* (with M Mendez)]()

[(2010). Elections and the internet: On the difficulties of upgrading elections in the digital era. Representation]()

[(2007) *The Governance and Regulation of the Internet in the European Union, the United States and Switzerland: A comparative federalism approach* EUI PhD Theses: Florence]()

[(2005). The European Union and cybercrime: insights from comparative federalism. *Journal of European Public Policy*]()

[(2005) *The European Union and E-Voting. Addressing the European Parliament’s Internet Voting Challenge, Routledge*. (with A Trechsel)]()

[(2004) Evaluation of the use of new technologies in order to facilitate democracy in Europe: E-democratizing the parliaments and parties of Europe. Study commissioned by the European Parliament (with Kies, R., Schmitter, P., & A. Trechsel)]()

##### Ongoing research
I am working with Uwe Serdült on a paper that exploits public voter registry data to explore the determinants of internet voting.

<br/>

## Machine learning
I am very interested in the application of supervised machine learning approaches to social science questions. In particular, I have been very keen to apply these methods to the analysis of vote choice while drawing on large N datasets of public opinion. Also, of interest is the use of such techniques for methodological aspects related to the analysis of opinion data, such as data cleaning. 

[(2017) Modeling proximity and directional decisional logic: What can we learn from applying statistical learning techniques to VAA-generated data? *Journal of Elections, Public Opinion and Parties*](https://doi.org/10.1080/17457289.2016.1269113)

[(2016) Mining online political opinion surveys for suspect entries: An interdisciplinary comparison, Journal of Innovation in Digital Ecosystems (with Djouvas, C. & N Tsapatsoulis)](https://www.researchgate.net/publication/311357308_Mining_online_political_opinion_surveys_for_suspect_entries_An_interdisciplinary_comparison)

[(2015) On the Design of Social Voting Recommendation Applications. *International Journal of Artificial Intelligence Tools* (Tsapatsoulis, N., Agathokleous, M., & C Djouvas)](https://www.researchgate.net/publication/272384379_On_the_Design_of_Social_Voting_Recommendation_Applications)

[(2014) Social Voting Advice Applications –Definitions, Challenges, Datasets and Evaluations. *IEEE Trasanctions on Cybernetics* (with Katakis, I., Tsapatsoulis, N., Triga, V. & K Djouvas)](https://doi.org/10.1109/TCYB.2013.2279019)

[(2014) Social Vote Recommendation: Building Party Models Using the Probability to Vote Feedback of VAA Users. SMAP 2014 Proceedings, IEEE Xplore (with N. Tsapatsoulis)](https://ieeexplore.ieee.org/document/6978966)

[(2014). Methodological challenges in the analysis of voting advice application generated data. SMAP 2014, IEEE Xplore (with Gemenis, K., & C Djouvas)](https://doi.org/10.1109/SMAP.2014.32)

<br/>

## Constitutional design
I have been interested in the area of comparative constitutional design and benefited in my research from working closely with constitutional lawyers. Most of the work focuses on how constitutional design can incorporate instruments of democratic participation.

[(2013) (eds) Patterns of constitutional design: The role of Citizens and elites in constitution–making. Ashgate (with J. Wheatley)]()

[(2013) The constitutional setting of the Republic of Sudan: A critical assessment. Report commissioned by the government of the Republic of Sudan (with Auer, A., & C Bisaz)]()

[(2011) The Transitional Constitution of the Republic of South Sudan 2011. Report commissioned by the government of the Republic of South Sudan (with Auer, A., & C Bisaz)]()

##### Ongoing research
My ongoing work in this domain is closely connected to my work within the
[LIDD](https://www.ivr.uzh.ch/en/institutsmitglieder/moeckli/Research-project-LIDD.html) ERC project (see Direct Democracy above)

